require "./spec_helper"

describe Pdf2Text::Extractor do
  it "rejects a file without %PDF- header" do
    File.write("/tmp/pdf2text-not-pdf.txt", "not a pdf")
    expect_raises(Pdf2Text::Extractor::ExtractError, /missing/) do
      Pdf2Text::Extractor.extract("/tmp/pdf2text-not-pdf.txt")
    end
  end

  it "extracts page count and dimensions from a real PDF" do
    # We assume a PDF exists in /tmp/pdfs-baseline-v81/ — the gold
    # baseline generated by crystal-asciidoctor-pdf. If not, skip.
    pdf = "/tmp/pdfs-baseline-v81/beryl.pdf"
    pending! "no baseline PDF at #{pdf}" unless File.exists?(pdf)

    extract = Pdf2Text::Extractor.extract(pdf)
    extract.pages.size.should be > 0
    extract.pages.first.width.should be > 0.0
    extract.pages.first.height.should be > 0.0
  end
end

describe Pdf2Text::Bbox do
  it "computes width and height" do
    b = Pdf2Text::Bbox.new(10.0, 20.0, 50.0, 100.0)
    b.width.should eq 40.0
    b.height.should eq 80.0
  end

  it "detects same-line bboxes (50% overlap rule)" do
    a = Pdf2Text::Bbox.new(0.0, 0.0, 100.0, 10.0)
    b = Pdf2Text::Bbox.new(110.0, 1.0, 200.0, 11.0)
    a.same_line?(b).should be_true
  end

  it "computes the gap between two bboxes" do
    a = Pdf2Text::Bbox.new(0.0, 0.0, 100.0, 10.0)
    b = Pdf2Text::Bbox.new(110.0, 0.0, 200.0, 10.0)
    a.gap_to(b).should eq 10.0
  end
end
